<<<<<<< HEAD
# Generated by Django 3.2 on 2023-07-27 12:35
=======
# Generated by Django 3.2 on 2023-07-30 06:57
>>>>>>> fix/users

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=1, verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
