# Generated by Django 3.2 on 2023-08-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20230731_1645'),
        ('review', '0003_auto_20230731_1042'),
    ]

    operations = [
    ]
