# Generated by Django 3.2 on 2023-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_merge_0002_auto_20230731_1645_0003_auto_20230731_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Идентификатор'),
        ),
    ]
