# Generated by Django 3.2 on 2023-08-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230805_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='title', through='reviews.TitleGenre', to='reviews.Genre'),
        ),
    ]
